# Generated by Django 3.2.12 on 2023-09-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tag',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
