# Generated by Django 3.2.12 on 2023-09-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_goods_ordertype_overallorderstatus_place_tagcolors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='OrderPlace',
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ordertype'),
        ),
    ]
