# Generated by Django 3.2.12 on 2023-09-14 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230913_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_class', models.CharField(choices=[('btn-primary', 'Blue'), ('btn-secondary', 'Gray'), ('btn-success', 'Green'), ('btn-danger', 'Red'), ('btn-warning', 'Yellow'), ('btn-info', 'Cyan'), ('btn-light', 'White')], default='btn-primary', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='places',
            field=models.ManyToManyField(blank=True, to='accounts.OrderPlace'),
        ),
        migrations.AddField(
            model_name='orderplace',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tagcolors'),
        ),
        migrations.AddField(
            model_name='ordertype',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tagcolors'),
        ),
    ]
