# Generated by Django 3.2.12 on 2023-09-14 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230914_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tagcolors'),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tagcolors'),
        ),
    ]
