# Generated by Django 3.2.12 on 2023-09-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230914_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='color',
            field=models.CharField(choices=[('btn-primary', 'Blue'), ('btn-secondary', 'Gray'), ('btn-success', 'Green'), ('btn-danger', 'Red'), ('btn-warning', 'Yellow'), ('btn-info', 'Cyan'), ('btn-light', 'White')], default='btn-primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertype',
            name='color',
            field=models.CharField(choices=[('btn-primary', 'Blue'), ('btn-secondary', 'Gray'), ('btn-success', 'Green'), ('btn-danger', 'Red'), ('btn-warning', 'Yellow'), ('btn-info', 'Cyan'), ('btn-light', 'White')], default='btn-primary', max_length=20),
        ),
    ]
